name: Publish website based on ipynbs

on:
  - push

jobs:
  website:
    name: Publish notebooks as website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-book-theme myst-nb sphinx-new-tab-link
      - name: Build website
        run: |
          sphinx-build -n --keep-going -b html ./ ./_build/
      - name: Publish workflow as website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
